{
 "title": "Invoices",
 "tags": [ "pfm" ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "customer",
    "query": "import \"influxdata/influxdb/schema\"\nschema.measurementTagValues(\nbucket: \"space1\",\ntag: \"client\",\nmeasurement: \"calentry\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Invoices",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"space1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"invoice\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"module\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"total\")"
    }
   ]
  },
  {
   "title": "Total invoiced (keuros)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"space1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"invoice\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> drop(columns: [\"client\", \"module\"])\n  |> sum()\n  |> map(fn: (r) => ({\n      r with\n      _value: r._value / 1000.0\n    })\n  )\n  |> yield(name: \"total\")"
    }
   ]
  },
  {
   "title": "Invoices total for customer (Keuros)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"space1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"invoice\")\n  |> filter(fn: (r) => r[\"client\"] == \"${customer}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |>sum()\n  |> map(fn: (r) => ({\n      r with\n      _value: r._value / 1000.0\n    })\n  )\n  |> drop(columns: [\"client\", \"_start\", \"_stop\", \"_field\"])\n  |> yield(name: \"total\")"
    }
   ]
  },
  {
   "title": "Number of invoices for customer",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"space1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"invoice\")\n  |> filter(fn: (r) => r[\"client\"] == \"${customer}\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> drop(columns: [\"client\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: count, createEmpty: false)\n  |> yield(name: \"total\")"
    }
   ]
  }
 ]
}