{
 "title": "Projects services",
 "tags": [ "pfm" ],
 "time": { "from": "now-90d", "to": "now" },
 "panels": [
  {
   "title": "Closed projects",
   "type": "table",
   "gridPos": { "h": 9, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  se_project.date_open,\n  se_project.date_close,\n  se_project.name,\n  cl_clients.name as client\nFROM se_project\nINNER JOIN cl_clients ON cl_clients.id=se_project.id_resp\nINNER JOIN se_visa ON se_visa.id=se_project.in_charge\nWHERE\n  $__timeFilter(se_project.created_at) AND se_project.deleted=0 AND se_project.date_close is not NULL\nORDER BY se_project.date_open"
    }
   ]
  },
  {
   "title": "Projects per client",
   "type": "table",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  cl_clients.name as client,\n  count(*) as projects\nFROM se_project\nINNER JOIN cl_clients ON cl_clients.id=se_project.id_resp\nWHERE\n  $__timeFilter(se_project.created_at) AND se_project.deleted=0 AND se_project.date_close is not NULL\nGROUP BY cl_clients.name\nORDER BY se_project.date_open"
    }
   ]
  },
  {
   "title": "Projects per responsible",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 11, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT\n  x.login as resp,\n  count(*) as projects\nFROM se_project\nINNER JOIN (SELECT users.login as login,se_visa.id_user as id_user,se_visa.id as id FROM users INNER JOIN se_visa ON se_visa.id_user=users.id) x\nON x.id=se_project.in_charge\nWHERE\n  $__timeFilter(se_project.created_at) AND se_project.deleted=0 AND se_project.date_close is not NULL\nGROUP BY x.login\nORDER BY se_project.date_open"
    }
   ]
  }
 ]
}