{
 "title": "Bookings",
 "tags": [ "pfm" ],
 "time": { "from": "now-90d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "resources",
    "query": "import \"influxdata/influxdb/schema\"\nschema.measurementTagValues(\nbucket: \"space1\",\ntag: \"resource\",\nmeasurement: \"calentry\")"
   },
   {
    "name": "customer",
    "query": "import \"influxdata/influxdb/schema\"\nschema.measurementTagValues(\nbucket: \"space1\",\ntag: \"client\",\nmeasurement: \"calentry\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Bookings",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"space1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"calentry\")\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> group(columns: [\"resource\"])\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Bookings for resource",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"space1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"calentry\")\n  |> filter(fn: (r) => r[\"resource\"] == \"${resources}\")\n  |> drop(columns: [\"client\",\"user\"])\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Total for ${resources}",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 16, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"space1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"calentry\")\n  |> filter(fn: (r) => r[\"resource\"] == \"${resources}\")\n  |> drop(columns: [\"client\",\"user\"])\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> sum(column: \"_value\")\n  |> yield(name: \"total\")"
    }
   ]
  },
  {
   "title": "Bookings for customer",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"space1\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"calentry\")\n  |> filter(fn: (r) => r[\"client\"] == \"${customer}\")\n  |> drop(columns: [\"client\",\"user\"])\n  |> filter(fn: (r) => r[\"_field\"] == \"value\")\n  |> aggregateWindow(every: v.windowPeriod, fn: sum, createEmpty: false)\n  |> yield(name: \"total\")"
    }
   ]
  }
 ]
}