name: PHP lint CI

on: [push, pull_request]

jobs:
  phplint:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v3
        - uses: overtrue/phplint@9.0.8
          with:
            path: .
            options: --exclude=*.log
